version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_ENV: production
    container_name: lightphp_app_prod
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
    environment:
      - APP_ENV=production
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: lightphp_db_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lightphp_prod
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data_prod:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data_prod:
