version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_ENV: development
    container_name: lightphp_app_dev
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html
    environment:
      - APP_ENV=development
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: lightphp_db_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lightphp_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data_dev:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data_dev:
